config/routes.rb
Gather::Application.routes.draw do
  
  resources :subjects do
     member do
        get 'close_dialog'
    end
  end

  resources :styles

  match 'question_images/:id/new' => 'question_images#new'
  resources :question_images
  devise_for :users
  
  match 'skip_logics/:question_id/new/' => 'skip_logics#new'
  
  
  match 'users/index' => 'users#index'
  match 'users/close_dialog' => 'users#close_dialog'
  
  match 'section/:id/questions/:type/new' => 'questions#new'
  match 'sections/close_dialog' => 'sections#close_dialog'
  resources :sections do
    member do
        post 'save_sort'
    end
    resources :questions
  end
  
  match 'statisticians/:id/password' => 'statisticians#password'
  match 'statisticians/close_dialog' => 'statisticians#close_dialog'
  resources :statisticians do 
    member do
        post 'save_sort'
        get 'close_dialog'
        get 'new_logo'
        get 'show_logo'
        get 'edit_logo'
        post 'update_logo'
        post 'create_logo'
    end
    resources :styles
    resources :sections 
  end
  
  resources :questions do
      resources :elements
  end
  
  resources :skip_logics
  resources :users

  #get "workbench/index"
  
  match 'workbench/:id' => 'workbench#index'
  match 'workbench/:id/power' => 'workbench#power'
  match 'workbench/:id/link' => 'workbench#link'
  match 'workbench/close' => 'workbench#close'
  match 'workbench/:id/results' => 'workbench#results'
  match 'workbench/:id/question_responses' => 'workbench#question_responses'
  match 'workbench/:id/export_results' => 'workbench#export_results'
  match 'workbench/:id/list_results/:page' => 'workbench#list_results'
  match 'workbench/:section_id/view_survey/:subject_id' => 'workbench#view_survey'
  
  resources :surveys do
    member do
      get 'css_style'
    end
  end
  #survey -------------------------------------------------------------------
  match 'surveys/:id/subject_authenticate/' => 'surveys#subject_authenticate'
  match 'surveys/:id/authenticate/' => 'surveys#authenticate'
  match 'surveys/:id/information/' => 'surveys#information'
  match 'surveys/:id/power/' => 'surveys#power'
  match 'surveys/:id/declined/' => 'surveys#declined'
  match 'surveys/:id/finish/' => 'surveys#finish'
  match 'surveys/:id/save/' => 'surveys#save'
  match 'surveys/:id/section/' => 'surveys#section'
  match 'surveys/:id/begin/' => 'surveys#begin'
  match 'surveys/:id/completed/' => 'surveys#completed'
  #match 'surveys/:id/css_style' => 'surveys#css_style'
  #--------------------------------------------------------------------------#
  
  root :to => "workbench#index"

end

app/controllers/workbench_controller.rb
require 'csv'
class WorkbenchController < ApplicationController
  before_filter :authenticate_user!#, :except => [:some_action_without_auth]
  
  def close
    #close dialog
  end
  
  def index
    @statisticians = nil
    
    if params[:id] == nil
      @statisticians = Statistician.all
    else
      @statisticians = Statistician.find(:all, :conditions => ['name LIKE ?', params[:id]+'%' ])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @statisticians }
    end
  end
  
  def power
    @statistician = Statistician.find(params[:id])
    #@response_count =  UserCompletedSurvey.count(:conditions => ['statistician_id = ?', @statistician.id])
    
    if @statistician.power == true
      Statistician.update(@statistician.id, :power => false)
    else
      Statistician.update(@statistician.id, :power => true)
    end
    
    redirect_to(:action => "index",:id => nil)
  end
  
  def link
    @statistician = Statistician.find(params[:id])
  end
  
  def results
    @statistician = Statistician.find(params[:id])
    @statistician.sections.each do |s|
      if @questions != nil then 
        @questions = @questions + s.questions
      else
        @questions = s.questions
      end
      #s.questions.each do |q|
        #if @results != nil then 
        #  @results = @results + q.responses
        #else 
        #  @results = q.responses
        #end
      #end
    end
  end
  
  def export_results
    @headers = Array.new
    @headers.push("Subject_id", "FirstName", "LastName", "DateCompleted")
    @statistician = Statistician.find(params[:id])
    @responses = UserCompletedSurvey.find(:all, :conditions => {:statistician_id => params[:id]})
    @statistician.sections.each do |s|
      if @questions != nil then 
        @questions = @questions + s.questions
      else
        @questions = s.questions
      end
    end
    
    @questions.each do |q|
       if q.question_type.is_multi_answer == true
          q.elements.each do |answer|
            @headers.push("#{q.question_text}-#{answer.element_text}")
          end
          if q.option_id  != nil and q.option.id == 3
            @headers.push("#{q.question_text}-#{q.option.name}")
          end
           
       else
          @headers.push(q.question_text)
          if q.option_id  != nil and q.option.id == 3
            @headers.push("#{q.question_text}-#{q.option.name}")
          end
       end
    end
    
    csv_string = CSV.generate do |csv| 
        csv << @headers
        #row = Array.new
        @responses.each do |r|
          row = Array.new
          row.push(r.subject.id)
          row.push(r.subject.first_name)
          row.push(r.subject.last_name)
          row.push(r.created_at)
          @questions.each do |q|
            if q.question_type.is_multi_answer == true
              q.elements.each do |answer|
                 response = Response.find(:all, :conditions => {:question_id => q.id, :element_id => answer.id, :subject_id => r.subject.id}).first
                 if response == nil
                   row.push(nil)
                 else
                   if response.answer_text != nil and response.answer_text != ''
                      row.push(response.answer_text)
                   else
                      row.push(response.element.element_text)
                   end
                 end
                 #response == nil ? row.push(nil) : row.push(response.element.element_text)
                 #row.push(response.element_id)
              end
              if q.option_id == 3 
                response = Response.where("question_id = ? and subject_id = ? and answer_text IS NOT NULL", q.id,r.subject.id).first
                if response != nil
                  row.push(response.answer_text)
                else
                  row.push(nil)
                end
              end
            else
              
              logger.debug "type : #{q.type.downcase}"
              if q.type.downcase == "freeform"
                response = Response.where("question_id = ? and subject_id = ?", q.id,r.subject.id).first
                row.push(response == nil ? nil : response.answer_text)
              else
                response = Response.where("question_id = ? and subject_id = ? and element_id IS NOT NULL", q.id,r.subject.id).first
                if response != nil
                  if response.answer_text != nil
                    row.push(response.answer_text)
                  else
                    row.push(response.element.element_text)
                  end
                else
                  row.push(nil)
                end
              end
           
              if q.option_id == 3 
                response = Response.where("question_id = ? and subject_id = ? and answer_text IS NOT NULL and element_id IS NULL", q.id,r.subject.id).first
                if response != nil
                  row.push(response.answer_text)
                else
                  row.push(nil)
                end
              end
                 #response = Response.find(:all, :conditions => {:question_id => q.id, :element_id => q.elements.first != nil ? q.elements.first.id : nil })
                 #response != nil ? row.push(response.element_id) : Response.find(:all, :conditions => {:question_id => q.id})
            end
          end
          csv << row
        end
        
    end
    send_data csv_string, 
            :type => 'text/csv; charset=iso-8859-1; header=present', 
            :disposition => "attachment; filename=results.csv" 
  end
  
  def question_responses
     @question = Question.find(params[:id])
     @responses = Response.find(:all, :conditions => ['question_id = ?', params[:id]])
     render :layout => "dialog"
  end
  
  def list_results
    @completed = UserCompletedSurvey.paginate(:conditions =>['statistician_id =?', params[:id]], :page => params[:page], :per_page => 20)
  end
  
  def view_survey
    @section = Section.find(params[:section_id])
    @subject_id = params[:subject_id]
    @statistician = @section.statistician
    session[:subject_id] = @subject_id
    @sections = Section.find(:all, :conditions => ["statistician_id = (?)", @section.statistician_id], :order => "sort_index")
    
    if params[:commit] == "Next"
         if @sections.index(@section) + 1 >= @sections.length
           redirect_to(:action => "list_results", :id => @section.statistician.id, :page => 1)
           return
         end
         redirect_to(:action => "view_survey",:section_id => @sections[@sections.index(@section) + 1].id, :subject_id => @subject_id)
         return 
    elsif params[:commit] == "Back"
      redirect_to(:action => "view_survey",:section_id => @sections[@sections.index(@section) - 1].id, :subject_id => @subject_id)
      return
    elsif params[:commit] == "Finish"
      redirect_to(:action => "list_results", :id => @section.statistician.id, :page => 1)
      return
    end
     
    render :layout => "statistician"
  end  
end

app/views/workbench/index.html.erb
<%= link_to image_tag("survey.png", :border => 0,:title => "Create new survey"), new_statistician_path %>
<%= link_to image_tag("new_subject.png", :border => 0, :title => "Add/View Subjects"), subjects_path %>
<%= link_to image_tag("users.png", :border => 0, :title => "Manage server users"), "/users/index" %>
<hr />
<table style="width:100%" class="alpha_paging">
<tr>
    <td>
        <%= link_to "All", :controller => "workbench", :action => "index", :id => nil %>
    </td>
    <td>
        <%= link_to 'A', :controller => "workbench", :id => 'a' %>
    </td>
    <td>
        <%= link_to 'B', :controller => "workbench", :id => 'b' %>
    </td>
    <td>
        <%= link_to 'C', :controller => "workbench", :id => 'c' %>
    </td>
    <td>
        <%= link_to 'D', :controller => "workbench", :id => 'd' %>
    </td>
    <td>
       <%= link_to 'E', :controller => "workbench", :id => 'e' %>
    </td>
    <td>
        <%= link_to 'F', :controller => "workbench", :id => 'f' %>
    </td>
    <td>
        <%= link_to 'G', :controller => "workbench", :id => 'g' %>
    </td>
    <td>
        <%= link_to 'H', :controller => "workbench", :id => 'h' %>
    </td>
    <td>
        <%= link_to 'I', :controller => "workbench", :id => 'i' %>
    </td>
    <td>
        <%= link_to 'J', :controller => "workbench", :id => 'j' %>
    </td>
    <td>
        <%= link_to 'K', :controller => "workbench", :id => 'k' %>
    </td>
    <td>
        <%= link_to 'L', :controller => "workbench", :id => 'l' %>
    </td>
    <td>
        <%= link_to 'M', :controller => "workbench", :id => 'm' %>
    </td>
    <td>
        <%= link_to 'N', :controller => "workbench", :id => 'n' %>
    </td>
    <td>
        <%= link_to 'O', :controller => "workbench", :id => 'o' %>
    </td>
    <td>
        <%= link_to 'P', :controller => "workbench", :id => 'p' %>
    </td>
    <td>
        <%= link_to 'Q', :controller => "workbench", :id => 'q' %>
    </td>
    <td>
        <%= link_to 'R', :controller => "workbench", :id => 'r' %>
    </td>
    <td>
        <%= link_to 'S', :controller => "workbench", :id => 's' %>
    </td>
    <td>
        <%= link_to 'T', :controller => "workbench", :id => 't' %>
    </td>
    <td>
        <%= link_to 'U', :controller => "workbench", :id => 'u' %>
    </td>
        <td>
        <%= link_to 'V', :controller => "workbench", :id => 'v' %>
    </td>
        <td>
        <%= link_to 'W', :controller => "workbench", :id => 'w' %>
    </td>
        <td>
        <%= link_to 'X', :controller => "workbench", :id => 'x' %>
    </td>
        <td>
        <%= link_to 'Y', :controller => "workbench", :id => 'y' %>
    </td>
        <td>
        <%= link_to 'Z', :controller => "workbench", :id => 'z' %>
    </td>
</tr>
</table>
<table class="datatable" style="width:100%">
  <tr>
    <th>Survey</th>
    <th>Responses</th>
    <th>Action</th>
  </tr>
 
<% @statisticians.each do |statistician| %>
  <tr class="<%= cycle('row', 'altrow') %>"
		onmouseover="this.className='althighlight'" 
    	onmouseout="this.className='row'" >
    <td>
		<span style="font-size:medium; color:Green;"><b><%= link_to statistician.name, statistician_sections_path(statistician) %></b></span><br />
		<span style="font-size:x-small; font-style:italic;"><b>Created:</b><%= statistician.created_at %></span>
		<span style="font-size:x-small; font-style:italic;"><b>Modified:</b><%= statistician.updated_at %></span>
	</td>
    <td><%= UserCompletedSurvey.count(:conditions => ['statistician_id = ?', statistician.id]) %></td>
    <td>
    	<%= link_to image_tag("edit.png", :border => 0, :title => "Edit survey"), edit_statistician_path(statistician) %> 
    	<%= link_to statistician.power == true ? image_tag("on.png", :border => 0, :title => "Survey is on") : image_tag("off.png", :border => 0, :title => "Survey is off"), :action => "power", :id => statistician.id %>
    	<%= link_to image_tag("link.png", :border => 0, :title => "Links for survey"), :action => "link", :id => statistician.id %>
    	<%= link_to image_tag("results.png", :border => 0, :title => "Results"), :action => "results", :id => statistician.id %>
    	</td>
  </tr>
<% end %>
<tr style="color:White; background-color:#77b108;">
    <th colspan="4">&nbsp;</th>
</tr>
</table>
<hr />

app/views/workbench/link.html.erb
<h1>Links</h1>
<hr />
URL: <%= link_to url_for(:controller => "surveys" ,:action => "begin", :only_path => false, :id => @statistician.id),
		:controller => "surveys", :action => "begin", :id => @statistician.id %>
<br />		
<br />
Embed Code: <br />
<%= text_area_tag 'link', 
	"<a href='#{url_for(:controller => "surveys" ,:action => "begin", :only_path => false, :id => @statistician.id)}'>your text here</a>",
		:cols => "80", :rows => "5" %>
<br />
<br />
<br />
<%= link_to "<< Back", :controller => "workbench", :action => "index", :id => nil %>

app/views/workbench/list_results.html.erb
<h3>Completed Surveys</h3>
<hr />
<table>
  <tr>
  	<th>
  		Respondant
  	</th>
  	<th>
  		Completed Date
  	</th>
  </tr>
  <% @completed.each do |response| %>
  <tr>
  	<td><a href=<%= "/workbench/#{response.statistician.sections.first.id}/view_survey/#{response.subject.id}"%>><%= response.subject.first_name %></a></td>
  	<td><%= response.created_at %></td>
  </tr>
    
  <% end %>
</table>

<hr />
<%= will_paginate @completed %>

app/views/workbench/question_responses.html.erb
<h2><%= @question.question_text %></h2>
<hr />
<table>
	<% @responses.each do |response|%>
	<tr class="<%= cycle('row', 'altrow') %>" style="width:100%">
		<td>
			<span style="font-size: smaller; font-style: italic"><b>created at:</b> <%= response.created_at.to_s %></span><br />
			<%= response.answer_text%>
	    </td>
	</tr>
	<%end%>
</table>
<hr />

app/views/workbench/results.html.erb
<script type="text/javascript">
function showResponsesDialog(question_id){
	$("#divId").dialog({ title: 'Viewing Responses' });
   	$("#divId").dialog("open");
   	$("#modalIframeId").attr("src","/workbench/" + question_id + "/question_responses");
   	return false;
}
$(document).ready(function() {
	$("#divId").dialog({
           autoOpen: false,
           modal: true,
           height: 500,
           width: 500,
           close: function(event, ui){ 
        		location.reload(true); 
       	   }
    });
});
</script>
<h2><%= @statistician.name %></h2>
Created Date: <b><%= @statistician.created_at.to_s %></b><br />
<hr />
Export: <%= link_to "CSV", "/workbench/#{@statistician.id}/export_results"%> || <%= link_to "View All", "/workbench/#{@statistician.id}/list_results/1"%>
<hr />
<% if @questions != nil %>
<% @questions.each do |result| %>
<% if result.is_sub %>
<div> Sub Question</div>
<%end%>
<div class="QuestionResponse"><%= result.question_text.html_safe %> </div>
<table class="AnswerResponses"> 
		<%result.elements.each do |e|%>
		<tr>
			<td class="AnswerResponse"><%= e.element_text %></td>
			<% if result.type.downcase == "scale" or result.type.downcase == "likert" then %>
				<% list = e.responses.map{ |x| x.answer_text }%>
				<% x = list.inject(Hash.new(0)) { |h, e| h[e] += 1 ; h } %> 
				<% if result.type.downcase == "likert" then %>
					<% columns = result.matrix_columns.split(",") %>
					<td class="ResponseCount">Most answered: <%= columns[list.sort_by { |v| x[v] }.last.to_i]%></td>
			    <% else %>
	            	<td class="ResponseCount">Most answered: <%= list.sort_by { |v| x[v] }.last%></td>
	            <% end %>
            <%else%>
				<td class="ResponseCount"><%= e.responses.length %></td>
				<td class="ResponsePercentage"><%= number_to_percentage(e.responses.length.to_f / result.responses.length.to_f * 100) %></td>
            <%end%>
            <td></td>
		</tr>
		<%end%>
	<tr>
		<td class="AnswerResponse"><b>Total</b></td>
		<td class="ResponseCount"><%= result.responses.length %></td>
		<td><% if result.type.downcase == "freeform" %><%= link_to_function "View responses","return showResponsesDialog(" + result.id.to_s + ");" %><%end%></td>
		<td></td>
	</tr>
</table>
<br />
<%end%>
<%end%>
<hr />
<div id="divId">
    <iframe id="modalIframeId" width="100%" height="100%"
    marginWidth="0" marginHeight="0" frameBorder="0" scrolling="auto"
    title="Dialog Title">Your browser does not support javascript... that is really messed up!</iframe>
</div>

app/views/workbench/view_survey.html.erb
<% content_for :survey_title, @section.statistician.name %>
<h3><%= @section.name %></h3>
<p><%= @section.description.html_safe %></p>
<hr />
<%= form_tag() %>
<% @section.questions.each do |q|%>	
	<% if q.is_sub == false %>
		<%= render :partial => "questions/" + q.class.name.downcase, :locals=>{:question=>q} %> 
		<% subs = q.sub_questions %>
		<% sub_questions = Array.new %>
		<% subs.each do |s|%>
			<% response = Response.where("question_id = :question_id and subject_id = :subject_id and element_id = :element_id",
					{:question_id => q.id,:subject_id => @subject_id, :element_id => s.element_id} ).first %>
			<% question = @section.questions.find_all{|item| item.id == s.question_sub_id}.first %>
			<% if response != nil %>
				<% question.is_hidden = false %>
			<% end %>
			<% sub_questions.push(question) %>
		<% end %>
		
		<% if sub_questions.length > 0 %>
			<% sub_questions = sub_questions.sort_by{|question| question.sort_index} %>
			<script>
					$("input[name='questions[<%=  q.id.to_s %>][answer_id]']").click(function () {
						
			<% subs.each do |sub|%>
						<% if sub.element_id != nil %>
	       					if ($("input[name='questions[<%=  q.id.to_s %>][answer_id]']:checked").val() == <%=sub.element_id.to_s%>){
	                			$('#branch_<%=sub.question_sub_id.to_s %>').show();
	       					}
	       					else{
	                			$('#branch_<%=sub.question_sub_id.to_s %>').hide();
	            			}
						<%end%>
			<% end %>
					});
			</script>
			<ul style=" list-style-type:none;">	
			<% sub_questions.each do |s|%>
				<li>
				<div id="branch_<%= s.id %>" <%if s.is_hidden == true%> style="display:none" <% end %> class="branch" >
					<%= render :partial => "questions/" + s.class.name.downcase, :locals=>{:question=>s} %> 
				</div>
				</li>
			<% end %>
			</ul>
		<% end %>
	<% end %>
<br />
<% end %>
<%if @section.statistician.sections.first.id != @section.id%>
<%= submit_tag("Back")%>
<% end %>
<%if @section.statistician.sections.last.id != @section.id%>
<%= submit_tag("Next")%>
<% end %>	
<%if @section.statistician.sections.last.id == @section.id%>
<%= submit_tag("Finish")%>
<% end %>
</form>
<hr />
<table>
<tr>
<% @section.statistician.sections.count.times do |i|%>
<% if @section.statistician.sections[i].id == @section.id %>
<td style=" background-color: Black; color:White"><%= (i + 1).to_s %></td>
<%else%>
<td><%= (i + 1).to_s %></td>
<%end%>
<% end %>
</tr>
</table>