config/routes.rb
Gather::Application.routes.draw do
  
  resources :subjects do
     member do
        get 'close_dialog'
    end
  end

  resources :styles

  match 'question_images/:id/new' => 'question_images#new'
  resources :question_images
  devise_for :users
  
  match 'skip_logics/:question_id/new/' => 'skip_logics#new'
  
  
  match 'users/index' => 'users#index'
  match 'users/close_dialog' => 'users#close_dialog'
  
  match 'section/:id/questions/:type/new' => 'questions#new'
  match 'sections/close_dialog' => 'sections#close_dialog'
  resources :sections do
    member do
        post 'save_sort'
    end
    resources :questions
  end
  
  match 'statisticians/:id/password' => 'statisticians#password'
  match 'statisticians/close_dialog' => 'statisticians#close_dialog'
  resources :statisticians do 
    member do
        post 'save_sort'
        get 'close_dialog'
        get 'new_logo'
        get 'show_logo'
        get 'edit_logo'
        post 'update_logo'
        post 'create_logo'
    end
    resources :styles
    resources :sections 
  end
  
  resources :questions do
      resources :elements
  end
  
  resources :skip_logics
  resources :users

  #get "workbench/index"
  
  match 'workbench/:id' => 'workbench#index'
  match 'workbench/:id/power' => 'workbench#power'
  match 'workbench/:id/link' => 'workbench#link'
  match 'workbench/close' => 'workbench#close'
  match 'workbench/:id/results' => 'workbench#results'
  match 'workbench/:id/question_responses' => 'workbench#question_responses'
  match 'workbench/:id/export_results' => 'workbench#export_results'
  match 'workbench/:id/list_results/:page' => 'workbench#list_results'
  match 'workbench/:section_id/view_survey/:subject_id' => 'workbench#view_survey'
  
  resources :surveys do
    member do
      get 'css_style'
    end
  end
  #survey -------------------------------------------------------------------
  match 'surveys/:id/subject_authenticate/' => 'surveys#subject_authenticate'
  match 'surveys/:id/authenticate/' => 'surveys#authenticate'
  match 'surveys/:id/information/' => 'surveys#information'
  match 'surveys/:id/power/' => 'surveys#power'
  match 'surveys/:id/declined/' => 'surveys#declined'
  match 'surveys/:id/finish/' => 'surveys#finish'
  match 'surveys/:id/save/' => 'surveys#save'
  match 'surveys/:id/section/' => 'surveys#section'
  match 'surveys/:id/begin/' => 'surveys#begin'
  match 'surveys/:id/completed/' => 'surveys#completed'
  #match 'surveys/:id/css_style' => 'surveys#css_style'
  #--------------------------------------------------------------------------#
  
  root :to => "workbench#index"

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :password
  validates :password, :uniqueness => true
  validates :identifier, :uniqueness => true
  has_many :responses
  has_many :user_completed_surveys
  
  def full_name 
    "#{self.first_name} #{self.middle_name} #{self.last_name}" 
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  def close_dialog
    #controller simply closes dialog see view for details
  end
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.where(:is_anonymous => :false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html { render :layout => "dialog" }# show.html.erb
      format.json { render :json => @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html { render :layout => "dialog" }# new.html.erb
      format.json { render :json => @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
    render :layout => "dialog"
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])
    @subject.password = Base64.encode64(Digest::SHA1.digest("#{rand(1<<64)}/#{Time.now.to_f}/#{Process.pid}"))[0..7]
    if @subject.identifier == nil || @subject.identifier == ""
      @subject.identifier = Base64.encode64(Digest::SHA1.digest("#{rand(1<<64)}/#{Time.now.to_f}/#{Process.pid}"))[0..7]
    end
    @subject.is_anonymous = false

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, :notice => 'Subject was successfully created.' }
        format.json { render :json => @subject, :status => :created, :location => @subject }
      else
        format.html { render :action => "new", :layout => "dialog" }
        format.json { render :json => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to(close_dialog_statistician_path(@subject))}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div >
	<%= f.label :first_name%><br />
	<%= f.text_field :first_name %>
  </div>
  <div >
	<%= f.label :middle_name%><br />
	<%= f.text_field :middle_name %>
  </div>
  <div >
	<%= f.label :last_name%><br />
	<%= f.text_field :last_name %>
  </div>
  <div >
	<%= f.label :email%><br />
	<%= f.email_field :email %>
  </div>
  <div >
	<%= f.label :identifier%><br />
	<%= f.text_field :identifier%>
  </div>
  <%if @subject.id != nil %>
	  <div >
		<%= f.label :password, "Access Code"%><br />
		<%= f.text_field :password %>
	  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/close_dialog.html.erb
<script type="text/javascript">
$(parent.document).find('.ui-dialog');
window.parent.$('#divId').dialog('close');
</script>

app/views/subjects/edit.html.erb
<%= render 'form' %>

app/views/subjects/index.html.erb
<script type="text/javascript">
function showEditDialog(id){
   $("#divId").dialog("open");
   $("#modalIframeId").attr("src", "/subjects/" + id + "/edit");
   return false;
}

function showNewDialog(){
   $("#divId").dialog({ title: 'New Subject' });
   $("#divId").dialog("open");
   $("#modalIframeId").attr("src", "<%= new_subject_path %>");
   return false;
}

$(document).ready(function() {
   $("#divId").dialog({
           autoOpen: false,
           modal: true,
           height: 500,
           width: 500,
           close: function(event, ui){ 
        		location.reload(true); 
       	   }
    });
});
</script>
<a href="" onclick="return showNewDialog();"><%= image_tag("add_subject.png", :border => 0, :title => "Add/View Subjects") %></a>
<hr />
<table class="datatable" style="width:100%">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Identifier</th>
    <th>Created</th>
    <th>Actions</th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
  	<td><a href="" onclick="return showEditDialog(<%= subject.id %>);"><%= subject.full_name %></a></td>
  	<td><%= subject.email %></td>
  	<td><%= subject.identifier %></td>
  	<td><%= subject.created_at %></td>
    <td><%= link_to image_tag("delete_survey.png", :border => 0), subject, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<tr style="color:White; background-color:#77b108;">
    <th colspan="5">&nbsp;</th>
</tr>
</table>

<hr />
<div id="divId" title="Edit subject">
    <iframe id="modalIframeId" width="100%" height="100%"
    marginWidth="0" marginHeight="0" frameBorder="0" scrolling="auto"
    title="Dialog Title">Your browser does not support</iframe>
</div>

app/views/subjects/new.html.erb
<%= render 'form' %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <b>First Name:</b>
  <%= @subject.first_name %>
</p>
<p>
  <b>Middle Name:</b>
  <%= @subject.middle_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @subject.last_name %>
</p>
<p>
  <b>Email:</b>
  <%= @subject.email %>
</p>
<p>
  <b>Access Code:</b>
  <%= @subject.password %>
</p>
<p>
	<b>Identifier:</b>
	<%= @subject.identifier%>
</p>