config/routes.rb
Gather::Application.routes.draw do
  
  resources :subjects do
     member do
        get 'close_dialog'
    end
  end

  resources :styles

  match 'question_images/:id/new' => 'question_images#new'
  resources :question_images
  devise_for :users
  
  match 'skip_logics/:question_id/new/' => 'skip_logics#new'
  
  
  match 'users/index' => 'users#index'
  match 'users/close_dialog' => 'users#close_dialog'
  
  match 'section/:id/questions/:type/new' => 'questions#new'
  match 'sections/close_dialog' => 'sections#close_dialog'
  resources :sections do
    member do
        post 'save_sort'
    end
    resources :questions
  end
  
  match 'statisticians/:id/password' => 'statisticians#password'
  match 'statisticians/close_dialog' => 'statisticians#close_dialog'
  resources :statisticians do 
    member do
        post 'save_sort'
        get 'close_dialog'
        get 'new_logo'
        get 'show_logo'
        get 'edit_logo'
        post 'update_logo'
        post 'create_logo'
    end
    resources :styles
    resources :sections 
  end
  
  resources :questions do
      resources :elements
  end
  
  resources :skip_logics
  resources :users

  #get "workbench/index"
  
  match 'workbench/:id' => 'workbench#index'
  match 'workbench/:id/power' => 'workbench#power'
  match 'workbench/:id/link' => 'workbench#link'
  match 'workbench/close' => 'workbench#close'
  match 'workbench/:id/results' => 'workbench#results'
  match 'workbench/:id/question_responses' => 'workbench#question_responses'
  match 'workbench/:id/export_results' => 'workbench#export_results'
  match 'workbench/:id/list_results/:page' => 'workbench#list_results'
  match 'workbench/:section_id/view_survey/:subject_id' => 'workbench#view_survey'
  
  resources :surveys do
    member do
      get 'css_style'
    end
  end
  #survey -------------------------------------------------------------------
  match 'surveys/:id/subject_authenticate/' => 'surveys#subject_authenticate'
  match 'surveys/:id/authenticate/' => 'surveys#authenticate'
  match 'surveys/:id/information/' => 'surveys#information'
  match 'surveys/:id/power/' => 'surveys#power'
  match 'surveys/:id/declined/' => 'surveys#declined'
  match 'surveys/:id/finish/' => 'surveys#finish'
  match 'surveys/:id/save/' => 'surveys#save'
  match 'surveys/:id/section/' => 'surveys#section'
  match 'surveys/:id/begin/' => 'surveys#begin'
  match 'surveys/:id/completed/' => 'surveys#completed'
  #match 'surveys/:id/css_style' => 'surveys#css_style'
  #--------------------------------------------------------------------------#
  
  root :to => "workbench#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gather</title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'gather.css' %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.13.custom.css' %>
  <%= javascript_include_tag 'jquery-ui-1.8.13.custom.min.js' %>
  <%= csrf_meta_tag %>
<script type="text/javascript">
function showLicense(){
	$("#license").dialog("open");
	return false;
}
$(document).ready(function() {
	$("#license").dialog({
           autoOpen: false,
           modal: true,
           height: 300,
           width: 500,
    });
    
    //$('form').submit(function(){
    //	$('input[type=submit]', this).attr('disabled', 'disabled');
	//});
});


</script> 
</head>
<body>
<div id="header" style="background-color:#fff; top:-10px; border-bottom: 1px solid #000;height:40px; width:100%;">
    <div id="title">
        <a href="/">
        <span style="font-size:xx-large; font-weight:bolder; font-family:Arial">✍</span>
        <span style="font-size:x-large;">Gather</span>
        </a>
    </div>  
    <div id="logindisplay" style="color:#000">
    	<% if user_signed_in? %>
    		<%= current_user.email%>
  			<%= link_to('Logout', destroy_user_session_path) %>        
		<% else %>
  			<%= link_to('Login', new_user_session_path)  %>  
		<% end %>
    </div> 
</div>
<div class="page" >
    <div id="main">
    	<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
            <%= yield %>
    </div>
</div>
<div id="footer" style="background:#4a7409;
   left:0px;
   bottom:0px;
   height:50px;
   width:100%;
   border-top: 1px solid black;color: White">
   <a href="https://github.com/ontehfritz/Gather/issues">Feature Request or Submit Bug</a> | <a href="" onclick="return showLicense();">License</a> | <a href="mailto:ontehfritz@gmail.com">Contact</a> | Version 0.3
   
<div id="license" title="MIT-LICENSE" style="display: none;">
<h3>Copyright 2012 http://www.gathersurvey.tk - Fritz (Fredrick) Seitz </h3>
<p>
Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:
</p>
<p>
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
</p>
<p>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
</p>
</div>
</div>
</body>
</html>

app/views/layouts/dialog.html.erb
<html>
<head>
  <title>Gather</title>
  <%= stylesheet_link_tag 'dialog.css' %>
  <%= javascript_include_tag 'jquery-1.6.1.min.js' %>
  <%= javascript_include_tag 'jquery-ui-1.8.13.custom.min.js' %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/layouts/statistician.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gather</title>
  <link href="<%= css_style_survey_path(@statistician,:css) %>" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'jquery-ui-1.8.13.custom.css' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="page">
	<div id="header">
		<div id="title">
        	<div id="logo">
        		<% if @statistician.file_name == nil %>
  	 				<%= image_tag("logo.png", :border => 0, :size => "50x50") %>
  				<% else %>
     				<%= image_tag(show_logo_statistician_url(@statistician), :alt => @statistician.name, :border => 0, :size => "50x50") %>
  				<% end %>
        	</div>
            <div id="statistician_name"><h2><%= yield :survey_title %></h2></div>
        </div>
        <div id="logindisplay">
        	&nbsp;
        </div> 
        <div id="menucontainer">
        	&nbsp;
        </div>
    </div>
    <div id="main">
    	<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
    	<%= yield %>
	    <div id="footer">
	    </div>
	</div>
</div>
</body>
</html>